# Generated by Django 4.1.7 on 2023-04-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post')),
            ],
        ),
    ]
