# Generated by Django 4.1.7 on 2023-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFood', '0002_rename_fecha_nacimiento_cliente_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='alergias',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='reserva',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='reserva',
            field=models.IntegerField(max_length=200),
        ),
    ]
